### ISSUE TITLE
Не ставится файл cert.pem

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_installer#13]
видимо изза того что устанавливает
CURL_CA_BUNDLE = C:\Program Files\NextGIS/share/ssl/certs/cert.pem

и еще переменная

SSL_CERT_FILE = C:\Program Files\NextGIS/share/ssl/certs/cert.pem

**Comment by BishopGIS** [comment]
В списке устанавливаемых файлов тут (https://github.com/nextgis/nextgis_installer/blob/master/qtifw_scripts/packages/com.nextgis.common.openssl/data/package.xml#L7) отсутсвует установка файлов в share.
Собственно установка файла тут (https://github.com/nextgis-borsch/lib_openssl/blob/master/apps/CMakeLists.txt#L38)
