### ISSUE TITLE
[Windows] Убрать сообщение об ошибке UAC авотризации

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/nextgis_installer#15]
На Windows при отмене UAC-авторизации в момент установки (нажатии "Нет") пользователю показывается такое окно:

![123456](https://cloud.githubusercontent.com/assets/6196272/23848314/baae6cde-07e7-11e7-85b6-641d5c342b07.PNG)

При нажатии на Abort - всё корректно завершается.
При нажатии на ОК - инсталлятор подвисает с надписью ("Не отвечает"), но потом всё корректно завершается.

Аналогичная ситуация в официальном инсталляторе Qt.

Нужно ли это убирать?

**Comment by BishopGIS** [comment]
Я считаю это не критичный баг (фича) - что-то на дальнюю перспективу. Возможно в Qt раньше подправят. Предлагаю перевести тикет в тип proposal. @simgislab что думаешь?

**Comment by simgislab** [comment]
тоже думаю пока не обязательно исправлять, поставил на 0.2

PS: я довольно жестко против использования лейбла proposal

**Comment by MikhanGusev** [comment]
Аналогичное происходит если просто начать устанавливать что-либо (и в нашем инсталлере и в Qt инсталлере) под не администраторской учётной записью на Win 7.

**Comment by MikhanGusev** [comment]
Убрать это нельзя и не следует, т.к. это особенность ОС Windows. При этом сделано:
1) Изменено сообщение на более читабельное;
2) Изменён путь по умолчанию на "Документы";

**Comment by simgislab** [comment]
эээ, какие Документы?! кто ставит туда программы, лучше на корень C:\NextGIS же

**Comment by MikhanGusev** [comment]
Неправильно написал, конечно. Не в документы, а в C:\Users\Mikhail\NextGIS, например. Т.е. в "Пользователи". Это определяется в Qt как "Home dir". В C:\ чуть посложнее будет логика: не у всех есть С:\ и не у всех С:\ может быть жёстким диском. Но можно и это сделать

**Comment by simgislab** [comment]
Миш, ну в Users тоже же никто не ставит программы, лучше C:\ с какой-то проверкой на наличие оного

**Comment by BishopGIS** [comment]
http://doc.qt.io/qtinstallerframework/scripting.html

Есть переменные которые определяют пути в целевой системе:

* RootDir
* HomeDir
* ApplicationsDir

На Маке ставится вот так @ApplicationsDir@/NextGIS что разворачивается в ```/Users/<user>/Application/NextGIS/```

Чем не подходит для Windows? Тут эта переменная развернется в ```C:/Program Files/NextGIS/``` 

Все равно давая пользователю право выбора пути ничего ему не помешает этот самый путь указать и в ручную. 

Переменная ApplicationsDir проверяет системный диск - где стоит ОС и правильно все это преобразует. Т.е. если С диска нет - будет D:/Program Files и т.д.

**Comment by MikhanGusev** [comment]
Проблема была в сути данного тикета: если пользователь без прав администратора, он не сможет поставить в Program Files, несмотря на то что этот путь всегда будет ему выдаваться в качестве дефолтного. 
Поменял на C:\NextGIS в итоге

**Comment by MikhanGusev** [comment]
> Миш, ну в Users тоже же никто не ставит программы, лучше C:\ с какой-то проверкой на наличие оного

Случайно увидел. Это по умолчанию, если что.
![456](https://cloud.githubusercontent.com/assets/6196272/26093987/c3f418f0-3a20-11e7-9182-bcbb182b19a3.PNG)
