### ISSUE TITLE
Иконки в меню Пуск и рабочий стол для QGIS

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_installer#16]
На рабочий стол только QGIS

В Пуск QGIS, документацию, обновление и удаление.

**Comment by alisovenko** [comment]
Исправил тут https://github.com/nextgis/nextgis_installer/commit/8b45cbe53a4b8a81f92e168dcc99f1f5b7383cae
Проверить можно тут: https://my.nextgis.com/downloads/software/installer/nextgis-dev-betta-setup.exe
Не закрываю т.к. доработка в отдельной ветке. Как сольем - закроем.

**Comment by simgislab** [comment]
сейчас все хорошо
