### ISSUE TITLE
Проблемы с базой проекций в NGQ

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_installer#18]
Несмотря на то что в базе проекции есть и перепроецирование работает - все равно что-то не так.

1. При загрузке любого векторного слоя через connect выскакивает предложение указать проекцию.

2. Вектор - Управление данными - Задать текущую проекцию вызывает ошибку

>IOError: [Errno 9] Bad file descriptor 
Traceback (most recent call last):
  File "C:\Program Files\NextGIS\share\ngqgis\python\plugins\fTools\tools\doDefineProj.py", line 162, in outProjFile
    print "AUTHID", projSelector.selectedAuthId()
IOError: [Errno 9] Bad file descriptor

**Comment by BishopGIS** [comment]
На всякий случай проверил на Маке - не воспроизводится.

**Comment by alisovenko** [comment]
На текущем QGIS (https://github.com/nextgis/nextgisqgis/commit/00eaec2ba6a423e3a2df11915029d3ffec1c45a8) и инсталляторе (https://github.com/nextgis/nextgis_installer/commit/75ca27e3f07c8c56834a21cad564bf66a2b112a3) ошибка не воспроизводится.
https://my.nextgis.com/downloads/software/installer/nextgis-dev-betta-setup.exe
Но еще буду наблюдать.

**Comment by alisovenko** [comment]
Ошибка есть.

**Comment by alisovenko** [comment]
Исправил (https://github.com/nextgis/nextgisqgis/commit/55d82aa592173cf42e1ca86ea963b796f84a6a4e).
Тут можно проверить https://my.nextgis.com/downloads/software/installer/nextgis-dev-betta-setup.exe
