### ISSUE TITLE
Sign Mac OS Desktop software with Apple dev cert

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#23]
https://docs.pexip.com/admin/mac_certificate.htm

**Comment by simgislab** [comment]
Если что, мы получали такой (?) для Метро вместе с @Kinda-me , надо проверить не он ли это

**Comment by Kinda-me** [comment]
У нас куплена подписка на Apple Developer Program (на Макса), до июля вроде действует. Но мы ее использовали только для размещения приложения в iTunes от имени NextGIS. А dev certificate генерировал Макс Смирнов со своего аккаунта, мы ничего такого не делали.

**Comment by BishopGIS** [comment]
Я нагенерировал сертификатов для Mac OS X - все работает.
