### ISSUE TITLE
Разделители панелей

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_installer#24]
Нельзя ли вернуть нормальные разделители.

Сейчас у меня так, много "палок":

![](http://m-d.me/img/ss/20170527-368-235kb.jpg)

А хотелось бы так:

![](http://m-d.me/img/ss/20170527-u08-253kb.jpg)

**Comment by BishopGIS** [comment]
Поменяй стиль и все

![2017-05-27 20 11 37](https://cloud.githubusercontent.com/assets/1708122/26523111/bb5ced9c-4318-11e7-9b6d-3b80dcb3016f.png)

А вообще тикет совсем не в тему. Для этого есть отдельный репозиторий и тикет сходный тоже есть. 
Вот же nextgis/nextgisqgis#1

**Comment by simgislab** [comment]
ok, @alisovenko а можно по умолчанию тогда сделать стиль без таких разделителей?

Тикеты там буду создавать)

**Comment by simgislab** [comment]
исправлено)
