### ISSUE TITLE
Increase input fields

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#3]
Increase input edit boxes size for login and password fields

![2016-12-22 11 52 41](https://cloud.githubusercontent.com/assets/1708122/21420186/33281150-c83d-11e6-94f4-456f67e2c12e.png)

**Comment by MikhanGusev** [comment]
![454545](https://cloud.githubusercontent.com/assets/6196272/23986659/51726d50-0a36-11e7-8c44-78fea41c74a9.PNG)

**Comment by BishopGIS** [comment]
Размеры не поменялись

![2017-04-21 23 23 37](https://cloud.githubusercontent.com/assets/1708122/25295054/a156aa22-26ea-11e7-9a8e-818da2baa428.png)

<img width="566" alt="2017-04-21 23 24 00" src="https://cloud.githubusercontent.com/assets/1708122/25295057/a59f769a-26ea-11e7-9c46-8df75d9264bd.png">

**Comment by BishopGIS** [comment]
Not necessary now
