### ISSUE TITLE
Suppress annoying warnings

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#32]
During uninstall/reinstall/update process installer show numerous annoying warnings. This is normal for our packets system install files to same directories. Need to suppress this warnings. 

```
Error during uninstallation process:
Cannot remove directory /Users/USER/Applications/NextGIS/usr/share: Directory not empty

Error during uninstallation process:
Cannot remove directory /Users/USER/Library/Python: Directory not empty
```

**Comment by MikhanGusev** [comment]
Fixed via removing of error messages in Mkdir operation
