### ISSUE TITLE
Добавить роль загрузчика.

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgis_installer#34]
Необходимо чтобы nextgisupdater умел запускать наше ПО.

Для чего:
если nextgisupdater вызван из QGIS, то после обновления компонентов он должен уметь запустить QGIS.

Пример реализации:

Добавить опцию запуска для nextgisupdater, чтобы можно было при старте указать какой исполняемый файл должен запустить nextgisupdater после обновления компонентов;
ИЛИ добавить опцию запуска для nextgisupdater, чтобы можно было указать с какими параметрами должен запускаться исполняемый файл
например:
nextgisupdater.exe --updater --launch c:\NextGIS-dev\bin\ngqgis --launch-options "c:\proj.qgs --opt1=qwe "

ИЛИ для получения опций запуска исполняемого фала попытаться из некоторого файла
из временной директории, который будет содержать перечень опций.
Имя файла можно передавать как опция nextgisupdater

возможны другие варианты?

@BishopGIS:
Я за вариант nextgisupdater.exe --updater --launch c:\NextGIS-dev\bin\ngqgis --launch-options "c:\proj.qgs --opt1=q"
Только в плане упрощения я бы сделал в launch все сразу что в execute process должно передаваться если так можно:
nextgisupdater.exe --updater --launch "c:\NextGIS-dev\bin\ngqgis c:\proj.qgs --opt1=qqq --opt2=www"

**Comment by simgislab** [comment]
это сначала к @MikhanGusev ?

**Comment by MikhanGusev** [comment]
Сделано. Вот пример вызова:

`nextgisupdater.exe --updater --launch "C:\NextGIS\bin\ngqgis.exe" --launch-options "C:\nextgis\test\for_installer_launch.qgs"`

**Comment by MikhanGusev** [comment]
@BishopGIS, с двумя опциями оказалось легче.

**Comment by alisovenko** [comment]
Все работает, закрываю.
