### ISSUE TITLE
Не работает плагин Rectangles Ovals Digitizing

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgis_installer#35]
Причина - использование согнала activated у объектов QAction.
Возможно следует собирать qt c поддержкой qt3, или это связано со сборкой pyqt4.

**Comment by BishopGIS** [comment]
@alisovenko Это разве не сюда? 
https://github.com/nextgis/nextgisqgis/issues

Плагин инсталлятора или QGIS?

**Comment by alisovenko** [comment]
Это сторонний плагин.
Подозреваю, что работоспособность плагина восстанавливается с помощью пересборки qt или pyqt.
Задачи по пакетам для инсталлятора мы сюда помещаем или нет?

**Comment by BishopGIS** [comment]
@simgislab @alisovenko Предлагаю закрыть в виду отсутвия заказчика/фидбэка

**Comment by simgislab** [comment]
переоткроем если появится поддержка на это
