### ISSUE TITLE
*.bat files are not created for *.py scripts

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_installer#38]
such as gdal_merge.bat for example

As a result QGIS GDALTools tools aren't working.

**Comment by BishopGIS** [comment]
May be fix GDALtools plugin to work not only with exe, but py files too?

**Comment by simgislab** [comment]
this is bad idea as GDALtools are deprecated in favor of Processing

GDALtools is just a side effect, *.bat files are good to have anyway in Windows

**Comment by BishopGIS** [comment]
You are not quite right.

1. We already modify gdaltools - https://github.com/nextgis/nextgisqgis/tree/master/opt/overwrite/python/plugins/GdalTools/tools
2. It's hard to create bat files for increasing amount of gdal py utilities. Also such duplication of files looks strange for enduser. And how it will be in console? Which one will be executed py or bat?

**Comment by BishopGIS** [comment]
It seems to me already fixed by @alisovenko
