### ISSUE TITLE
QGIS не запускается с ошибкой QtGui4.dll

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_installer#52]
Запустил Updater. Сначала обновился он сам, потом нашёл обновления ко всем пакетам на 240 мб. После завершения работы, NextGIS QGIS на компьютере не оказалось.
При следующем запуске updater нашел те же обновления ко всем пакетам, поставил, QGIS появился, но не запускается с сообщением:
![image](https://user-images.githubusercontent.com/4630662/41940430-5ad30176-79a1-11e8-9fed-a9cae3d0f616.png)

**Comment by BishopGIS** [comment]
Если все удалить и поставить заново ошибка воспроизводится?

**Comment by BishopGIS** [comment]
No feedback
