### ISSUE TITLE
Use normal OAuth2 backend for user/pass auth

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgis_installer#6]
https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2
See **Grant Type: Resource Owner Password Credentials**

**Comment by BishopGIS** [comment]
See OAuth 2 in [Qt Network Authentication](https://doc-snapshots.qt.io/qt5-5.8/qtnetworkauth-index.html) in Qt 5.8

**Comment by BishopGIS** [comment]
NextGIS installer no longer requires any authentication. The installer downloaded executable and desktop software do require them now.
