### ISSUE TITLE
User update notification

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#7]
XML format of update information has such format:
```xml
<updates>
    <update name="Qt Creator 4.2.0" size="321764085" version="4.2.0-0"/>
    <update name="macOS" size="854379474" version="5.7.1-0"/>
    <update name="Qt 5.7" size="0" version="5.7.1-0"/>
    <update name="Qt Charts" size="0" version="5.7.1-0"/>
    <update name="Qt WebEngine" size="0" version="5.7.1-0"/>
    <update name="Qt 5.7 Examples" size="81075550" version="5.7.1-0"/>
    <update name="Documentation for Qt5.7 GPLv3 components (QtCharts)" size="16351812" version="5.7.1-0"/>
    <update name="Examples for Qt5.7 GPLv3 components (QtCharts)" size="503452" version="5.7.1-0"/>
    <update name="Documentation for QtWebEngine" size="8829901" version="5.7.1-0"/>
    <update name="Qt 5.7 Documentation" size="429555229" version="5.7.1-0"/>
    <update name="Examples for QtWebEngine" size="1516850" version="5.7.1-0"/>
    <update name="Maintenance Tool" size="32653639" version="2.0.4-2"/>
    <update name="Qt Charts for macOS" size="16970124" version="5.7.1-0"/>
    <update name="Qt WebEngine for macOS" size="2878191918" version="5.7.1-0"/>
</updates>
```

QGIS notification dialog should show a table:

|Name | Version | Size |
|------|---------|------|
|Qt Creator 4.2.0|4.2.0-0|321Mb|
|macOS|5.7.1-0|854Mb|
|Qt 5.7|5.7.1-0| |

and so on

**Comment by BishopGIS** [comment]
Вот пример диалога обновления
<img width="812" alt="2017-01-28 21 04 08" src="https://cloud.githubusercontent.com/assets/1708122/22398620/840f70b8-e59d-11e6-9f24-6ea6601b2c6f.png">

**Comment by simgislab** [comment]
этот пример для нас не очень подходит, так как загрузка осуществляется молча в фоне и потом нужно только перезапустить

**Comment by BishopGIS** [comment]
Почему так не сделать? Тоже вариант.

**Comment by BishopGIS** [comment]
Кажется сейчас реализовано? Закрываем?
@simgislab @alisovenko

**Comment by simgislab** [comment]
я не совсем понял что сделано, тут намешано всего. В первой части идет про то, чтобы уведомлять пользователя о новых версиях и в приложениях (кугис, фб), про это есть тикет про ченджлог.

а потом о silent update

может стоит и вправду закрыть, но перенести про silent update в отдельный тикет

**Comment by BishopGIS** [comment]
Так вроде все сделано в плане обновления из самого софта - разве что-то еще нужно в этом плане? Я думаю текущая реализация годная и можно этот тикет закрывать.

**Comment by simgislab** [comment]
вообще много еще чего нужно :) но закрыть действительно можно, еще вернемся к этой теме, как будет возможность.
