### ISSUE TITLE
Rebuild installer with Qt 5.8

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#8]
Now Qt have config to create lite version (~5Mb). 
See https://habrahabr.ru/post/320284/#qt-lite

It may reduce size of installer application.

**Comment by MikhanGusev** [comment]
Updated to Qt 5.8.0 but without size reducing of the final installer exe. Reason - installer depends on qttools module which itself depends on all qt widgets - so we cannot remove unnesessary widgets from the qtbase during statical building of Qt. Possible fix is to remove this dependancy

**Comment by MikhanGusev** [comment]
Uitools dependency removed. Installer size is reduced from 16.5 to 14.8 Mb.
